services:
  - type: web
    name: your-laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: composer install
    startCommand: /bin/bash -c "service php8.1-fpm start && nginx -g 'daemon off;'"
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_DEBUG
        value: true
