services:
  - type: web
    name: your-laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: composer install
    startCommand: php-fpm
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_DEBUG
        value: true
